### ISSUE TITLE
Avoid usage of GraphDatabaseService in plugins

### ISSUE THREAD

**Issue by DirkMahler** [kontext-e/jqassistant-plugins#58]
Since jQA 1.3.0 it is possible to connect to running remote instances of Neo4j, in this case `org.neo4j.graphdb.GraphDatabaseService` is not available. For portability the plugins should either use XO based mappings or execute Cypher queries using the store interface.

**Comment by kontext-e** [comment]
Tried to use Cypher queries using the store interface:
final Query.Result<Query.Result.CompositeRowObject> compositeRowObjects = store.executeQuery("CREATE (n:" + label.name() + ") RETURN n");
		final Query.Result.CompositeRowObject singleResult = compositeRowObjects.getSingleResult();
		final Object id = singleResult.getId();

Result:
 ERROR ScannerImpl - Unexpected problem encountered while scanning: item='git\src\test\java\de\kontext_e\jqassistant\plugin\git\scanner\JGitScannerTest.java', path='/java/de/kontext_e/jqassistant/plugin/git/scanner/JGitScannerTest.java', scope='NONE', pipeline='[com.buschma
is.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@7f190e12, de.kontext_e.jqassistant.plugin.javaparser.scanner.JavaparserScannerPlugin@1e660313]'. Please report this error including the full stacktrace (continueOnError=true).
com.buschmais.xo.api.XOException: Cannot find proxy for method 'public abstract <I> I com.buschmais.xo.api.CompositeObject.getId()'
        at com.buschmais.xo.impl.proxy.AbstractProxyMethodService.invoke(AbstractProxyMethodService.java:24)
        at com.buschmais.xo.impl.proxy.query.RowInvocationHandler.invoke(RowInvocationHandler.java:20)
        at com.sun.proxy.$Proxy134.getId(Unknown Source)
        at de.kontext_e.jqassistant.plugin.javaparser.scanner.MyGraphDatabaseService.executeQuery(MyGraphDatabaseService.java:22)

Do I use it in a wrong way or does XO not really support Cypher queries?

**Comment by DirkMahler** [comment]
CompositeRowObject represents a row consisting of named columns, 
you'll need to execute:

```
CompositeObject compositeObject = singleResult.get("n", CompositeObject.class);
Object id = compositeObject.getId();
```

Nevertheless providing getId() for CompositeRowObject seems a bit odd, should be removed.

**Comment by kontext-e** [comment]
BTW. this works:
		final Query.Result<Query.Result.CompositeRowObject> compositeRowObjects = store.executeQuery("CREATE (n" + labelsClause + ") RETURN id(n)");
		final Query.Result.CompositeRowObject singleResult = compositeRowObjects.getSingleResult();
		int id = ((Number)singleResult.get("id(n)", Object.class)).intValue();

**Comment by kontext-e** [comment]
Your suggestion produces a stracktrace: 

`ERROR ScannerImpl - Unexpected problem encountered while scanning: item='javaparser\src\test\java\de\kontext_e\jqassistant\plugin\javaparser\scanner\ExampleSourceFile.java', path='/java/de/kontext_e/jqassistant/plugin/javaparser/scanner/ExampleSourceFile.java', scope='NONE
', pipeline='[com.buschmais.jqassistant.plugin.common.impl.scanner.FileResourceScannerPlugin@60d932a4, de.kontext_e.jqassistant.plugin.javaparser.scanner.JavaparserScannerPlugin@74df1739]'. Please report this error including the full stacktrace (continueOnError=true).
com.buschmais.xo.api.XOException: Cannot create an instance of a single abstract type [EntityTypeMetadata[JavaSourceDescriptor]]
        at com.buschmais.xo.impl.AbstractInstanceManager.validateTypes(AbstractInstanceManager.java:114)
        at com.buschmais.xo.impl.AbstractInstanceManager.getInstance(AbstractInstanceManager.java:94)
        at com.buschmais.xo.impl.AbstractInstanceManager.readInstance(AbstractInstanceManager.java:56)
        at com.buschmais.xo.impl.query.QueryResultIterableImpl$1.decodeValue(QueryResultIterableImpl.java:76)
        at com.buschmais.xo.impl.query.QueryResultIterableImpl$1.next(QueryResultIterableImpl.java:51)
        at com.buschmais.xo.impl.AbstractResultIterable.getSingleResult(AbstractResultIterable.java:16)
        at de.kontext_e.jqassistant.plugin.javaparser.scanner.MyGraphDatabaseService.createNode(MyGraphDatabaseService.java:24)
`

**Comment by DirkMahler** [comment]
XO tries to map found nodes to types. According to the error in your case there's only one matching interface and it seems to be declared as @Abstract, so this is the intended behavior.

**Comment by kontext-e** [comment]
Indeed, and I was sure that this one was not Abstract...

**Comment by kontext-e** [comment]
Will be in 1.4.1
